import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Blob {

    private String fileName, sha1Text;
    private static String fileContents;

    public Blob(String fileName) {
        this.fileName = fileName;

    }

    public String getFileName() {
        return fileName;
    }

    public String getSha1() {
        return sha1Text;
    }

    public String getFileContents() {
        return fileContents;
    }

    // Java program to calculate SHA-1 hash value
    public void fileToSHA1() throws NoSuchAlgorithmException {
        // getInstance() method is called with algorithm SHA-1
        MessageDigest md = MessageDigest.getInstance("SHA-1");

        // digest() method is called
        // to calculate message digest of the input string
        // returned as array of byte
        byte[] messageDigest = md.digest(fileContents.getBytes());

        // Convert byte array into signum representation
        BigInteger no = new BigInteger(1, messageDigest);

        // Convert message digest into hex value
        sha1Text = no.toString(16);

        // Add preceding 0s to make it 32 bit
        while (sha1Text.length() < 32) {
            sha1Text = "0" + sha1Text;
        }
    }

    // Driver code
    public static void main(String args[]) throws NoSuchAlgorithmException {

        System.out.println("HashCode Generated by SHA-1 for: ");

        String s1 = "GeeksForGeeks";
        // System.out.println("\n" + s1 + " : " + encryptThisString(s1));

        String s2 = "hello world";
        // System.out.println("\n" + s2 + " : " + encryptThisString(s2));
    }
}