import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Blob {

    private String fileName, sha1Text;
    private static String fileContents;

    public Blob(String fileName) throws IOException { // grabs existing file on disk w fileName
        // blob files are the file contents
        this.fileName = fileName;
        fileContents = "";
        BufferedReader br = new BufferedReader(new FileReader(fileName));
        while (br.ready()) {
            fileContents += (char) (br.read());
        }
        br.close();
    }

    public String getFileName() {
        return fileName;
    }

    public String getSha1() {
        return sha1Text;
    }

    public String getFileContents() {
        return fileContents;
    }

    // Java program to calculate SHA-1 hash value
    public void fileToSHA1() throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        byte[] messageDigest = md.digest(fileContents.getBytes());
        BigInteger no = new BigInteger(1, messageDigest);
        sha1Text = no.toString(16);
        while (sha1Text.length() < 32) {
            sha1Text = "0" + sha1Text;
        }
    }

    public void writeToObjFolder() {
        // File file = new File ("")
    }

    // Driver code
    public static void main(String args[]) throws NoSuchAlgorithmException {

        System.out.println("HashCode Generated by SHA-1 for: ");

        String s1 = "GeeksForGeeks";
        // System.out.println("\n" + s1 + " : " + encryptThisString(s1));

        String s2 = "hello world";
        // System.out.println("\n" + s2 + " : " + encryptThisString(s2));
    }
}